### ISSUE TITLE
Support for LLM2VEC models?

### ISSUE THREAD

**Issue by sandeep-krutrim** [MinishLab/model2vec#105]
Hi

Thanks for this great work !

It would be awesome if you can provide distillation support for LLM2VEC models. Sentence Transformer currently doesnt have a support for LLM2VEC and hence it is not possible to use it for distillation.

Thanks

**Comment by stephantul** [comment]
Hello @sandeep-krutrim, thanks for reaching out!

We don't use sentence-transformers to distill models, just plain `transformers`. We basically just do a forward pass, nothing fancy. I'm not familiar with the library itself, so I don't know what would be needed to properly support them.

If you have a clear example of how you do a forward pass, we could add support or tell you how it could work.

Stéphan

**Comment by stephantul** [comment]
Hello, I'm closing this for now because of inactivity.

Let me know if you need more help!
Stéphan
