### ISSUE TITLE
KeyError: 'special_tokens'"

### ISSUE THREAD

**Issue by david-waterworth** [MinishLab/model2vec#106]
I have a fine-tuned SentenceTransfomers model based on "sentence-transformers/all-mpnet-base-v2" which I'm trying to distill - but it fails with a KeyError: 'special_tokens'" at https://github.com/MinishLab/model2vec/blob/9c73fdf195e0ba053e2953b36b4d89b02e76f2e5/model2vec/distill/tokenizer.py#L79

The tokenizer (which I think is based on Roberta) doesn't have a `special_tokens` key in the it's post-processor, you could perhaps rely on "added_tokens" (which has a `special` key)? 

To replicated:

```
from transformers import AutoTokenizer
import json

tokenizer = AutoTokenizer.from_pretrained("sentence-transformers/all-mpnet-base-v2")
tokenizer_data = json.loads(tokenizer.backend_tokenizer.to_str())

tokenizer_data["post_processor"]["special_tokens"]  # <-- error

[t for t in tokenizer_data["added_tokens"] if t['special']]  # <-- works for this tokenizer (I think?)
```

Full stack trace:

{
	"name": "KeyError",
	"message": "'special_tokens'",
	"stack": "---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[3], line 1
----> 1 static_embedding = StaticEmbedding.from_distillation(\"models/pipelines-jna3414jup2l-TrainModel-7QAP8Rr4Az\", device=\"cpu\", pca_dims=256)
      2 model = SentenceTransformer(modules=[static_embedding])

File .venv/lib/python3.10/site-packages/sentence_transformers/models/StaticEmbedding.py:169, in StaticEmbedding.from_distillation(cls, model_name, vocabulary, device, pca_dims, apply_zipf, use_subword)
    164     raise ImportError(
    165         \"To use this method, please install the `model2vec` package: `pip install model2vec[distill]`\"
    166     )
    168 device = get_device_name()
--> 169 static_model = distill(
    170     model_name,
    171     vocabulary=vocabulary,
    172     device=device,
    173     pca_dims=pca_dims,
    174     apply_zipf=apply_zipf,
    175     use_subword=use_subword,
    176 )
    177 if isinstance(static_model.embedding, np.ndarray):
    178     embedding_weights = torch.from_numpy(static_model.embedding)

File .venv/lib/python3.10/site-packages/model2vec/distill/distillation.py:189, in distill(model_name, vocabulary, device, pca_dims, apply_zipf, use_subword)
    186 model: PreTrainedModel = AutoModel.from_pretrained(model_name)
    187 tokenizer: PreTrainedTokenizerFast = AutoTokenizer.from_pretrained(model_name)
--> 189 return distill_from_model(
    190     model=model,
    191     tokenizer=tokenizer,
    192     vocabulary=vocabulary,
    193     device=device,
    194     pca_dims=pca_dims,
    195     apply_zipf=apply_zipf,
    196     use_subword=use_subword,
    197 )

File .venv/lib/python3.10/site-packages/model2vec/distill/distillation.py:91, in distill_from_model(model, tokenizer, vocabulary, device, pca_dims, apply_zipf, use_subword)
     89 wrong_token_ids = [vocab[token] for token in wrong_tokens]
     90 # Remove the unused tokens from the tokenizer.
---> 91 new_tokenizer = remove_tokens(tokenizer.backend_tokenizer, wrong_tokens)
     92 # Remove the embeddings of the unused tokens.
     93 embeddings = np.delete(embeddings, wrong_token_ids, axis=0)

File .venv/lib/python3.10/site-packages/model2vec/distill/tokenizer.py:79, in remove_tokens(tokenizer, tokens_to_remove)
     76     raise ValueError(f\"Unknown model type {model_type}\")
     78 # Reindex the special tokens (i.e., CLS and SEP for BertTokenizers.)
---> 79 special_tokens_post_processor: dict[str, dict] = tokenizer_data[\"post_processor\"][\"special_tokens\"]
     80 for token, token_data in special_tokens_post_processor.items():
     81     token_data[\"ids\"] = [reindexed[token] for token in token_data[\"tokens\"]]

KeyError: 'special_tokens'"
}

**Comment by stephantul** [comment]
Hey @david-waterworth,

Thanks for the bug report! This should not be happening. I'll investigate, and will get back to you shortly.

Stéphan

**Comment by stephantul** [comment]
Fix is in PR #107 . Thanks for reporting! Should be merged soon. I don't know when we'll release this, we might go for a quick bugfix release.

**Comment by stephantul** [comment]
Hi @david-waterworth ,

I accidentally closed this because I merged the PR. Sorry about that. If you want, you can pull main and retry. I think it should work.

**Comment by stephantul** [comment]
Hi @david-waterworth,

this is now released in a new version on Pypi. Please update, and let us know how it goes. I'm closing this for now.

Thanks!
Stéphan
