### ISSUE TITLE
Number of tokens (151646) does not match number of vectors (151643)

### ISSUE THREAD

**Issue by su-park** [MinishLab/model2vec#108]
Hello.

I tried testing `model2vec` in the following environment and encountered the error below. Is there a way to resolve this?

### Environment

```python
model2vec==0.3.0
tokenizers==0.19.1
```

### Code

```python
from model2vec.distill.distillation import distill

# Choose a Sentence Transformer model
model_id = "Alibaba-NLP/gte-Qwen2-7B-instruct"

# Distill an output model with the chosen dimensions
model = distill(model_name=model_id, device="cpu", pca_dims=256)
```

### Error

```python
Value Error: Number of tokens (151646) does not match number of vectors (151643)
```

**Comment by stephantul** [comment]
Hey @su-park ,

Thanks for reporting! This shouldn't be happening, I'll take a look as soon as possible. 

Stéphan

**Comment by stephantul** [comment]
Hey, I figured it out. Somehow, the number of tokens of the backend tokenizer and the number of tokens in the HF tokenizer doesn't match. 

```python
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("Alibaba-NLP/gte-Qwen2-7B-instruct")
tokenizer.vocab_size
# 151643
tokenizer.backend_tokenizer.get_vocab_size()
# 151646
tokenizer.get_vocab()
# 151646
```

I checked, and there are definitely 151646 tokens in the vocabulary, not 15643. So I think the `vocab_size` being off by three is actually a bug in Transformers, not a bug in `model2vec`. In the mean-time, we could rely on the length of the vocabulary instead. I'll open a PR to change this.

**Comment by stephantul** [comment]
PR is here #109 . 

I'll see if we can push this together with #107 and release a bugfix release soon.

**Comment by stephantul** [comment]
I accidentally closed this because I merged the PR. Sorry about that. If you want, you can pull main and retry. I think it should work.

**Comment by su-park** [comment]
Thank you for your swift support.

It worked!
