### ISSUE TITLE
AttributeError: 'tokenizers.Tokenizer' object has no attribute 'encode_batch_fast'

### ISSUE THREAD

**Issue by su-park** [MinishLab/model2vec#111]
Hello.
I encountered one more issue when testing `model2vec` in the following environment:
You can avoid the error by changing `self.tokenize.encode_batch_fast` to `self.tokenize.encode_batch`.

### Environment

```python
model2vec==0.3.0
tokenizers==0.19.1
```

### Code

```python
from model2vec.distill.distillation import distill

# Choose a Sentence Transformer model
model_id = "Alibaba-NLP/gte-Qwen2-7B-instruct"

# Distill an output model with the chosen dimensions
model = distill(model_name=model_id, device="cpu", pca_dims=256)

emb = model.encode(["안녕하세요", "Hello"])
```

### Error

```python
AttributeError: 'tokenizers.Tokenizer' object has no attribute 'encode_batch_fast'
```

**Comment by stephantul** [comment]
Hello @su-park,

`encode_batch_fast` was added in tokenizers 0.20. Could you confirm that you have installed a version >= 0.20? If this the case, then we need to provide a work-around for tokenizers that don't have this function, and fall back to `encode_batch`.

Thanks!
Stéphan

**Comment by su-park** [comment]
Oh, I didn’t know that.
I worked around it by installing `tokenizers==0.19.1` due to the MTEB package and its dependencies.
Thank you for checking.
