### ISSUE TITLE
About the reported scores on MSMARCO

### ISSUE THREAD

**Issue by twadada** [MinishLab/model2vec#132]
Hi, according to the MTEB GitHub repository (https://github.com/embeddings-benchmark/mteb), models should be evaluated on the "dev" split on MSMARCO, but it seems your code might produce the scores on the test set. Could you confirm whether this is actually the case; if so, could you update the scores (incl. the MTEB average score) accordingly?

Best,

**Comment by stephantul** [comment]
Hello!

Thanks for bringing this to our attention! We'll rectify this error as soon as possible.
Let me know if you have further questions.

Stéphan
