### ISSUE TITLE
Using Model2Vec for Token Classification

### ISSUE THREAD

**Issue by kelayamatoz** [MinishLab/model2vec#137]
Hi Model2Vec Team,

This is truely great work, thanks so much for the contribution! Awesome project!

One dumb question: Is it possible to apply model2vec to a token classification model, e.g., BERT model connected to a NER tagger?

I've been playing with Model2Vec, and seems that for now it is designed to only output embedding for a whole sequence (e.g., [CLS]). It seems that Model2Vec currently does not support generating embeddings for every token in a sequence. Is this understanding correct?

If so, how would you recommend that I augment Model2Vec to support generating token-level embeddings, and potentially drop it into a NER tagger?

Thank you!

**Comment by Pringled** [comment]
Hi @kelayamatoz,

Thanks for the kind words! You can actually use Model2Vec for that purpose out of the box, the following should work:

```python
from model2vec import StaticModel

# Load a model from the HuggingFace hub (in this case the potion-base-8M model)
model = StaticModel.from_pretrained("minishlab/potion-base-8M")

# Make sequences of token embeddings
token_embeddings = model.encode_as_sequence(["It's dangerous to go alone!", "It's a secret to everybody."])
```

This will give you the individual token embedding for every input token. Let me know if this works for you or if you have any other questions!

**Comment by kelayamatoz** [comment]
This works perfectly -- thank you for the pointer! My apologies, I just realized that the tutorial does include token embedding examples, and I somehow overlooked them. Sorry about that!
