### ISSUE TITLE
Models distilled using model2vec cannot work on SentenceTransformers

### ISSUE THREAD

**Issue by asfoorial** [MinishLab/model2vec#41]
The below code fails! is there any way to make your generated model to be compatible with sbert?

from sentence_transformers import SentenceTransformer
model = SentenceTransformer("minishlab/M2V_base_output")

**Comment by Pringled** [comment]
Hi @asfoorial,

Thanks for this request. We plan to add compatibility for Sentence Transformers soon, I will let you know once that's been released.

**Comment by Pringled** [comment]
Hi, Model2Vec is now supported in Sentence Transformers since the latest release: https://github.com/UKPLab/sentence-transformers/releases/tag/v3.2.0. Closing this for now, if you have other questions feel free to open a new issue!
