### ISSUE TITLE
Document 

### ISSUE THREAD

**Issue by riyajatar37003** [MinishLab/model2vec#48]
Hi,
It's very interesting.
I am going through it ,but can you share any documentation or resources for better understanding of it's foundation or how it works internally?

Thanks 👍

**Comment by Pringled** [comment]
Hi @riyajatar37003,

Thanks for your question! We are working on a blogpost at the moment that explains the techniques used in more detail. We plan to publish this soon, I'll let you know here once that's published.

**Comment by Pringled** [comment]
We've just published a blogpost where we explain the architecture more, you can find it here: https://huggingface.co/blog/Pringled/model2vec. If you do have any other questions or feel that documentation is missing in some places, feel free to open a new issue!
