### ISSUE TITLE
Error with embeddings model jinaai/jina-embeddings-v3

### ISSUE THREAD

**Issue by drdsgvo** [MinishLab/model2vec#52]
Model source: https://huggingface.co/jinaai/jina-embeddings-v3
code:
m2v_model = distill(model_name="jinaai/jina-embeddings-v3", pca_dims=256, device="cuda")

With or without using the pca_dims parameter, I get the following error:

   m2v_model = distill(model_name="jinaai/jina-embeddings-v3", device="cuda")
  File "/home/km/.local/lib/python3.10/site-packages/model2vec/distill/distillation.py", line 58, in distill
    tokens, embeddings = create_output_embeddings_from_model_name(
  File "/home/km/.local/lib/python3.10/site-packages/model2vec/distill/inference.py", line 127, in create_output_embeddings_from_model_name
    intermediate_weights.append(out[:, 1].cpu().numpy())
TypeError: Got unsupported ScalarType BFloat16

Any idea on this?

**Comment by stephantul** [comment]
Hey, interesting. It turns out the jina model is quantized to `bfloat16`, but this isn't supported by `numpy`. 

We'll push a fix for this and release when possible. Thanks for reporting!

**Comment by stephantul** [comment]
This is now in PR: https://github.com/MinishLab/model2vec/pull/53

I'll ping you once it gets to main. This model still doesn't work, unfortunately, because it uses a unigram tokenizer, which we don't support yet. I'll add that as well. Sorry for the issues!

**Comment by stephantul** [comment]
The second part is also in PR: #54 

I am able to load the Jina model after both of these things are fixed. I'll let you know once they are in main.

**Comment by stephantul** [comment]
Hellooo,

this is now fixed on main. We don't support adding vocabularies for unigram and BPE yet, this is on our roadmap, but the commands above should work now. We're releasing later today, so you can also wait for that.

I am closing this, feel free to re-open if you have more issues/questions/it doesn't work.

Stéphan
