### ISSUE TITLE
💀 Distillation not working megathread 💀 

### ISSUE THREAD

**Issue by stephantul** [MinishLab/model2vec#55]
Hi,

We tested model2vec on a whole bunch of models, but it is definitely possible that it doesn't work on a specific model. If this is the case, you can report them here. This can help us to prioritize the right models.

Thanks! 💘 
Thomas & Stéphan

**Comment by NikosKont** [comment]
Hi, tried on [Qwen/Qwen2.5-Coder-1.5B](https://huggingface.co/Qwen/Qwen2.5-Coder-1.5B/tree/main), it ran smoothly until the end, but then I got "ValueError: Number of tokens (151665) does not match number of vectors (151643)".
[traceback.txt](https://github.com/user-attachments/files/17528924/traceback.txt)
Any idea what could have caused this?
Thanks

**Comment by FahadEbrahim** [comment]
Hi, 

PLBART is one of the models as per the issue (https://github.com/MinishLab/model2vec/issues/115).

Thanks,
Fahad.
