### ISSUE TITLE
Unexpected keyword argument 'token_type_ids' on distilling sentence-transformers/distiluse-base-multilingual-cased-v2

### ISSUE THREAD

**Issue by AltamashRafiq** [MinishLab/model2vec#90]
Encountered TypeError: DistilBertModel.forward() got an unexpected keyword argument 'token_type_ids'
Version: model2vec==0.2.4
Python: 3.10.14
Reproducible example:

```
from model2vec import distill

base_model_name = "sentence-transformers/distiluse-base-multilingual-cased-v2"
model = distill(model_name=base_model_name, pca_dims=256)
```

**Comment by AltamashRafiq** [comment]
It appears that a fix for this issue was added 5 days ago: https://github.com/MinishLab/model2vec/commit/84570b680b7ee49aeb0bb8267a6612b8f42b6af7

Perhaps this will be part of the next release? When is the next release expected?

**Comment by stephantul** [comment]
Hey @AltamashRafiq,

This will be part of the next release, yeah. Sorry about that. Our current main branch has some breaking changes wrt sentence-transformers. So we might go back and just release this fix, which we might be able to do today. 

I'll keep you posted!
Stéphan

**Comment by AltamashRafiq** [comment]
Thanks! Also thank you for the great work you folks are doing developing this tool!

**Comment by stephantul** [comment]
@AltamashRafiq Hey! The release including this fix is live: https://pypi.org/project/model2vec/0.3.0/

I'm closing this, please re-open if you encounter more issues. Happy modeling!
